apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
  labels:
    app: eureka
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
  selector:
    app: eureka