apiVersion: v1
kind: ServiceAccount
metadata:
  name: weave-scope
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "original-request": {
          "url": "/k8s/v1.8/scope.yaml",
          "date": "Fri Jun 21 2019 19:24:30 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
  labels:
    name: weave-scope
  namespace: weave