apiVersion: v1
kind: Service
metadata:
  name: tomcat-api-common-svc
  labels:
    app: tomcat
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
    nodePort: 30004
  selector:
    app: tomcat-api-common
