kind: PersistentVolume
apiVersion: v1
metadata:
  name: tomcat-api-common-pv
  labels:
    type: local
spec:
  storageClassName: sc-local
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/hdd/tomcat-api-common"
