apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openresty-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openresty
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
        - name: openresty-pod
          image: openresty/openresty
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/etc/nginx/conf.d"
              name: openresty-conf
      nodeSelector:
        node_type: node
      volumes:
        - name: openresty-conf
          persistentVolumeClaim:
            claimName: openresty-pvc