kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/hdd/nginx/www"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv-conf
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/hdd/nginx/conf"