apiVersion: v1
kind: Service
metadata:
  name: prom-node-exporter-svc
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: node-exporter-expose
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    k8s-app: node-exporter