apiVersion: v1
kind: Service
metadata:
  name: prom-node-exporter-headless
  namespace: kube-system
  labels:
    k8s-app: node-exporter
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    k8s-app: node-exporter