apiVersion: v1
kind: Service
metadata:
  name: jfrog-artifactory-svc
  labels:
    app: jfrog-artifactory
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30018
  selector:
    app: jfrog-artifactory