apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: jfrog-artifactory-pv-data
      labels:
        type: local
    spec:
      storageClassName: sc-local
      capacity:
        storage: 30Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain 
      hostPath:
        path: "/media/hdd/jfrog-artifactory/data"
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: jfrog-artifactory-pv-logs
      labels:
        type: local
    spec:
      storageClassName: sc-local
      capacity:
        storage: 30Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain 
      hostPath:
        path: "/media/hdd/jfrog-artifactory/logs"
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: jfrog-artifactory-pv-etc
      labels:
        type: local
    spec:
      storageClassName: sc-local
      capacity:
        storage: 30Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain 
      hostPath:
        path: "/media/hdd/jfrog-artifactory/etc"