apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: nginx-ss
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx:latest
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: nginx-volume
      spec:
        storageClassName: sc-local
        resources:
          requests:
            storage: 4Gi
        accessModes:
          - ReadWriteOnce
