kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry-pvc
spec:
  storageClassName: sc-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  volumeName: docker-registry-pv