kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-registry-pv  
  labels:
    type: local
spec:
  storageClassName: sc-local  
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/hdd/docker-registry"
