apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: docker-registry-dp
spec:
  selector:
    matchLabels:
      app: docker-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry-pod
          image: registry:2
          ports:
            - containerPort: 5000
              name: docker-registry
          volumeMounts:
            - name: storage-repo
              mountPath: /var/lib/registry
              readOnly: false
      volumes:
        - name: storage-repo
          persistentVolumeClaim:
            claimName: docker-registry-pvc