kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv
  labels:
    type: local
spec:
  storageClassName: sc-local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/nginx/html"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv-conf
  labels:
    type: local
spec:
  storageClassName: sc-local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/nginx/conf"