apiVersion: v1
kind: Service
metadata:
  name: apicurio-svc
  labels:
    app: apicurio
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30020
    name: apicurio
  - protocol: TCP
    port: 8443
    targetPort: 8443
    nodePort: 30021
    name: apicurio-studio
  selector:
    app: apicurio