apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 4
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: minio/minio:RELEASE.2019-03-06T22-47-10Z
        args:
        - server
        - http://minio-0.minio.default.svc.cluster.local/data/
        - http://minio-1.minio.default.svc.cluster.local/data/
        - http://minio-2.minio.default.svc.cluster.local/data/
        - http://minio-3.minio.default.svc.cluster.local/data/
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: sc-local
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
