# apiVersion: v1
# kind: Service
# metadata:
#   name: minio
#   labels:
#     app: minio
# spec:
#   clusterIP: None
#   ports:
#     - port: 9000
#       name: minio
#   selector:
#     app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio