apiVersion: v1
kind: Service
metadata:
  name: tomcat-api-user-svc
  labels:
    app: tomcat
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003
  selector:
    app: tomcat-api-user
