kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tomcat-api-user-pvc
spec:
  storageClassName: sc-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeName: tomcat-api-user-pv
